# netlify.toml

[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  # As linhas external_node_modules não são necessárias para @google/generative-ai com esbuild


# Redirecionamentos existentes (mantenha os que você usa)
[[redirects]]
  from = "/api/get-motivation"
  to = "/.netlify/functions/get-motivation"
  status = 200

[[redirects]]
  from = "/api/get-training-tips"
  to = "/.netlify/functions/get-training-tips"
  status = 200

# --- Novo Redirecionamento para a função de geração de imagem com Gemini ---
[[redirects]]
  from = "/api/generate-image-gemini" # Novo endpoint para a API Gemini
  to = "/.netlify/functions/generate-image-gemini" # Nome do novo arquivo da função
  status = 200

# Se você não precisar mais da função FLUX/Gradio, pode remover o redirecionamento:
# [[redirects]]
#   from = "/api/generate-image-flux"
#   to = "/.netlify/functions/generate-image-flux"
#   status = 200

# Seu build settings (já deve existir)
[build]
  publish = "public"
  functions = "netlify/functions"

# Seus cabeçalhos de segurança
[[headers]]
  for = "/*" # Aplica-se a todas as rotas
  [headers.values]
    # Content Security Policy (ajuste conforme necessário para o seu site)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://pagead2.googlesyndication.com https://www.highperformanceformat.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://www.googletagmanager.com https://blogmotivacionalai.netlify.app; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://frasesmotivacionaisapi.com; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # Referrer Policy (escolha a opção que melhor se adapta à sua privacidade/analytics)
    Referrer-Policy = "no-referrer-when-downgrade"
    
    # X-Content-Type-Options
    X-Content-Type-Options = "nosniff"

    # Outros cabeçalhos de segurança úteis (opcional, mas recomendado)
    X-Frame-Options = "DENY" # Previne clickjacking (se não usa iframes para incorporar seu conteúdo)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload" # Força HTTPS (se já usa HTTPS)
    Permissions-Policy = "geolocation=(), microphone=(), camera=()" # Controla acesso a APIs do navegador