# netlify.toml

[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install" # Garante que as dependências sejam instaladas durante o deploy

[functions]
  node_bundler = "esbuild"
  # A linha abaixo foi removida pois não usamos mais @google-cloud/aiplatform
  # external_node_modules = ["@google-cloud/aiplatform"]
  # Se você tiver outras dependências que precisam ser "externalizadas", adicione-as aqui.
  # Por exemplo, se você notar problemas com 'node-fetch' ou 'axios'
  # external_node_modules = ["node-fetch", "axios"] # Adicione apenas se houver problemas específicos


# Redirecionamentos para suas funções Netlify
[[redirects]]
  from = "/api/get-motivation"
  to = "/.netlify/functions/get-motivation"
  status = 200

[[redirects]]
  from = "/api/get-training-tips"
  to = "/.netlify/functions/get-training-tips"
  status = 200

# Redirecionamento para a nova função de geração de imagens com Hugging Face
[[redirects]]
  from = "/api/generate-image-flux" # Este será o endpoint que seu frontend chamará
  to = "/.netlify/functions/generate-image-flux" # Corresponde ao nome do arquivo da sua função (generate-image-flux.js)
  status = 200