# netlify.toml
[build]
  publish = "public"      
  functions = "netlify/functions" 
  command = "npm install" 

[functions]
  node_bundler = "esbuild" 
  external_node_modules = ["@google-cloud/aiplatform"] 

# Redirecionamentos opcionais
[[redirects]]
  from = "/api/get-motivation"
  to = "/.netlify/functions/get-motivation"
  status = 200

[[redirects]]
  from = "/api/get-training-tips"
  to = "/.netlify/functions/get-training-tips"
  status = 200