# netlify.toml

# Configurações de build
[build]
  publish = "public"
  functions = "netlify/functions"
  # O comando de build foi ajustado para apenas instalar as dependências.
  # Seu projeto não tem um script 'build', então removemos essa parte para evitar a falha.
  command = "npm install"

# =======================
# Seção de Plugins
# =======================

# Plugin para gerar o sitemap automaticamente
# Este deve ser o primeiro plugin para gerar o sitemap.xml
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    # O diretório onde os arquivos de build são publicados
    buildDir = "public"

# Plugin para submeter o sitemap gerado aos motores de busca
# Este plugin deve vir depois do @netlify/plugin-sitemap
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    # URL base do seu site (substitua por sua URL real)
    baseUrl = "https://blogmotivacionalai.netlify.app"
    sitemapPath = "/sitemap.xml"
    providers = ["google", "yandex"]

# Plugin para gerar relatórios de Lighthouse
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# =======================
# Configurações de Funções
# =======================

[functions]
  node_bundler = "esbuild"

# =======================
# Redirecionamentos de rotas
# =======================

[[redirects]]
  from = "/api/get-motivation"
  to = "/.netlify/functions/get-motivation"
  status = 200

[[redirects]]
  from = "/api/get-training-tips"
  to = "/.netlify/functions/get-training-tips"
  status = 200

[[redirects]]
  from = "/api/generate-image-gemini"
  to = "/.netlify/functions/generate-image-gemini"
  status = 200

# =======================
# Cabeçalhos de Segurança
# =======================

[[headers]]
  for = "/*"
  [headers.values]
   Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://descendedlibrarian.com https://willplug.com https://www.googletagmanager.com https://pagead2.googlesyndication.com https://www.highperformanceformat.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://descendedlibrarian.com https://willplug.com https://www.googletagmanager.com https://blogmotivacionalai.netlify.app https://rqnytipqrrusoukeqowr.supabase.co https://thenpreservationticket.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' data: https://frasesmotivacionaisapi.com www.google-analytics.com https://professionaltrafficmonitor.com https://thenpreservationticket.com"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    