# netlify.toml
[build]
  publish = "public"      # Diretório onde seu index.html e outros arquivos estáticos estão
  functions = "netlify/functions" # Diretório onde suas Netlify Functions estão
  command = "npm install" # Ou "yarn install" se você usar Yarn

[functions]
  node_bundler = "esbuild" # Para builds mais rápidas de funções Node.js
  # REMOVA A LINHA ABAIXO se você a adicionou anteriormente
  # node_version = "18" # <-- ESTA LINHA DEVE SER REMOVIDA

# Redirecionamentos opcionais para URLs mais amigáveis (ex: /api/get-motivation)
# Se você usar isso, lembre-se de atualizar o fetch() no seu frontend!
[[redirects]]
  from = "/api/get-motivation"
  to = "/.netlify/functions/get-motivation"
  status = 200

[[redirects]]
  from = "/api/get-training-tips"
  to = "/.netlify/functions/get-training_tips"
  status = 200